### ISSUE TITLE
v4.7.20 deprecated in PHP 8.1.3

### ISSUE THREAD

**Issue by alanwojcik** [inspector-apm/inspector-laravel#25] opened 2022-03-08 08:28 UTC
**Describe the bug**
On PHP 8.1.3, when using inspector-laravel 4.7.20 we're getting PHP Deprecated in log:
[08-Mar-2022 09:20:26 Europe/Warsaw] PHP Deprecated:  Return type of Inspector\Models\Arrayable::offsetExists($key) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /[...]/vendor/inspector-apm/inspector-php/src/Models/Arrayable.php on line 112

**To Reproduce**
Install inspector-laravel on Laravel 9 with PHP 8.1.3, look for error log

**Comment by ilvalerione** [comment] 2022-03-08 11:38
Hi @alanwojcik thank you for reporting the issue. I'll update you when the fix is released.

**Comment by websolutionfalcon** [comment] 2022-03-23 14:41
@ilvalerione +1
We cannot use inspector service because of the issue. Please fix it ASAP

**Comment by ilvalerione** [comment] 2022-03-23 15:27
Hi, the issue was caused by the @inspector-apm/inspector-php basic library. It was fixed by the latest reòease 3.7.9

Run composer update to get the latest version.

**Closed** 2022-03-23 15:36 UTC
